In [ ]:
import torch

In [ ]:
torch.rand(2,4)

tensor([[0.4582, 0.2115, 0.2724, 0.7422],
        [0.6751, 0.6371, 0.1660, 0.5390]])

## Tensor and Vector

**Vector:** A one-dimensional collection of values that can represent both magnitude and direction.

**Tensor:** A generalized multi-dimensional data structure that includes scalars, vectors, and matrices.

**Summary:** Every vector can be considered a tensor, specifically a one-dimensional tensor.

In [ ]:
scalar = torch.tensor(7)
print(scalar)
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Shape of scalar: {scalar.shape}")

tensor(7)
Dimension of scalar: 0
Shape of scalar: torch.Size([])


In [ ]:
vec = torch.tensor([1,2,3,4])
print(vec)
print(f"Dimension of vec: {vec.ndim}")
print(f"Shape of vec: {vec.shape}")

tensor([1, 2, 3, 4])
Dimension of vec: 1
Shape of vec: torch.Size([4])


In [ ]:
ten = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])

print(f"Dimension of ten: {ten.ndim}")
print(f"Shape of ten: {ten.shape}")

Dimension of ten: 3
Shape of ten: torch.Size([1, 3, 3])


In [ ]:
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Comparison of Scalar, Vector, and Tensor (Using the Defined Variables)

**Scalar (`scalar`):**
- **Dimension:** 0
- **Shape:** `torch.Size([])`
- *Simply a single number.*

**Vector (`vec`):**
- **Dimension:** 1
- **Shape:** `torch.Size([4])`
- *A one-dimensional list of numbers.*

**Tensor (`ten`):**
- **Dimension:** 3
- **Shape:** `torch.Size([1, 3, 3])`
- *A multi-dimensional array, a generalization of numbers and lists.*

**In a nutshell:**
- A **scalar** is a 0-dimensional tensor.
- A **vector** is a 1-dimensional tensor.
- A **tensor** can be any N-dimensional data structure.

## Overview of Common `torch` Tensor Creation Functions

*   **`torch.rand(shape)`**: Creates a tensor with the specified `shape` and populates it with random numbers uniformly distributed between 0 and 1.
*   **`torch.zeros(shape)`**: Creates a tensor with the specified `shape` and fills it with zeros.
*   **`torch.ones(shape)`**: Creates a tensor with the specified `shape` and fills it with ones.
*   **`torch.eye(n)`**: Creates a 2D identity matrix (a square matrix with ones on the main diagonal and zeros elsewhere) of size `n`x`n`.
*   **`torch.arange(start, end, step)`**: Creates a 1D tensor with values from `start` (inclusive) to `end` (exclusive), with a specified `step` size.
*   **`torch.linspace(start, end, steps)`**: Creates a 1D tensor with `steps` number of equally spaced points between `start` and `end` (both inclusive).

In [ ]:
rand = torch.rand(3,4)
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
eye = torch.eye(3)
arange = torch.arange(start=0, end=10, step=2)
linspace = torch.linspace(start=0, end=10, steps=5)

print(f"rand: {rand}")
print(f"zeros: {zeros}")
print(f"ones: {ones}")
print(f"eye: {eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")


rand: tensor([[0.5988, 0.3680, 0.3243, 0.5963],
        [0.4293, 0.1409, 0.6462, 0.2746],
        [0.4236, 0.3860, 0.2197, 0.6181]])
zeros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


# **Tensor Arithmetic Operations**

## Difference Between `+` Operator and `torch.add()`

Both the `+` operator and `torch.add()` perform element-wise addition of tensors. However, there's a subtle difference in their behavior regarding memory allocation and broadcasting:

*   **`+` operator**: This is an overloaded Python operator that generally creates a new tensor to store the result of the addition. It's often more readable and idiomatic for simple operations.

*   **`torch.add(input, other, *, alpha=1, out=None)`**: This is a function that provides more control. It also creates a new tensor by default, but it allows for an optional `out` argument where you can specify an existing tensor to store the result. This can be beneficial for memory management in performance-critical scenarios, as it avoids creating new memory if an `out` tensor is provided and reused. It also supports an `alpha` parameter to scale `other` before adding. When `out` is not provided, both behave similarly.

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])

print(a+b)
print(a-b)
print(a*b)

# adding using add()
print(torch.add(a,b))

print(torch.add(a, b, alpha=2))  # steps (a + bx)

tensor([4, 6, 8])
tensor([-2, -2, -2])
tensor([ 3,  8, 15])
tensor([4, 6, 8])
tensor([ 7, 10, 13])


## Comparing `@` and `*` in Tensor Multiplication

When working with `torch` tensors:

*   **`*` (Element-wise Multiplication)**: This operator performs element-wise multiplication (also known as Hadamard product). It requires the tensors to have compatible shapes (either the same shape or broadcastable to the same shape). Each element in the first tensor is multiplied by the corresponding element in the second tensor.

*   **`@` (Matrix Multiplication)**: This operator performs matrix multiplication (or dot product for 1D tensors). It has specific shape requirements: for two matrices `A` (m x n) and `B` (n x p), the result `C` will be (m x p). The number of columns in the first matrix must match the number of rows in the second matrix. For 1D tensors, it performs a dot product.

In [ ]:
# Element-wise multiplication (*)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"Tensor A: {a}")
print(f"Tensor B: {b}")
print(f"Element-wise multiplication (A * B): {a * b}")

# Matrix multiplication (@)
mat_a = torch.tensor([[1, 2],
                      [3, 4]])
mat_b = torch.tensor([[5, 6],
                      [7, 8]])

print(f"\nMatrix A: {mat_a}")
print(f"Matrix B: {mat_b}")
print(f"Matrix multiplication (A @ B): {mat_a @ mat_b}")

# Example with 1D tensors (dot product)
vec_a = torch.tensor([1, 2, 3])
vec_b = torch.tensor([4, 5, 6])

print(f"\nVector A: {vec_a}")
print(f"Vector B: {vec_b}")
print(f"Dot product (Vector A @ Vector B): {vec_a @ vec_b}")

Tensor A: tensor([1, 2, 3])
Tensor B: tensor([4, 5, 6])
Element-wise multiplication (A * B): tensor([ 4, 10, 18])

Matrix A: tensor([[1, 2],
        [3, 4]])
Matrix B: tensor([[5, 6],
        [7, 8]])
Matrix multiplication (A @ B): tensor([[19, 22],
        [43, 50]])

Vector A: tensor([1, 2, 3])
Vector B: tensor([4, 5, 6])
Dot product (Vector A @ Vector B): 32


### Understanding the Memory Behavior of `reshape()` and `view()`

The crucial distinction lies in whether the new tensor *shares memory* with the original tensor (a **view**) or if it creates a *completely new block of memory* (a **copy**).

*   **`tensor.view()`**: This method always attempts to return a **view**. This means the new tensor does not allocate new memory; it just presents the existing memory in a different shape. Because it shares memory, if you change an element in the `view` tensor, the original tensor will also change, and vice-versa. However, `view()` requires the original tensor to be **contiguous** in memory. If the original tensor is not contiguous (e.g., after transposing), `view()` will fail unless you call `.contiguous()` first, which *might* create a copy to make it contiguous.

*   **`tensor.reshape()`**: This method is more flexible. It will first try to return a **view** (sharing memory) if the memory layout allows it (i.e., if the tensor is contiguous and the new shape is compatible without reordering data). If the memory layout does not allow for a view (e.g., the tensor is not contiguous, or the new shape would require reordering elements that are not adjacent in memory), `reshape()` will automatically return a **copy** of the data in new memory. Changes to a copied tensor will *not* affect the original, and vice-versa.

**In summary:**
*   `view()`: Always a view (memory shared), but strict contiguity requirement.
*   `reshape()`: Prefers a view (memory shared) if possible, otherwise makes a copy (new memory). This makes `reshape()` generally safer and more convenient, as you don't have to worry about contiguity.

In [ ]:
t = torch.arange(1,10,1)  # numbers from 1-9 with step-size 1

print(t.reshape(3,3))  # converting t to 3x3 tensor
print(t.view(3,3))
print(t)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
x = torch.tensor([[1.], [2.], [3.]])
# squeeze(): Removes dimensions of size 1 from the tensor.
print(x.squeeze())
# unsqueeze(dim): Adds a dimension of size 1 at the specified position (dim).
print(x.unsqueeze(0))

tensor([1., 2., 3.])
tensor([[[1.],
         [2.],
         [3.]]])


In [ ]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.tensor([7, 8, 9])
# torch.stack(): Concatenates a sequence of tensors along a new dimension.
# Here, dim=0 means a new dimension is added at the beginning, stacking t1 and t2 row-wise.
print(torch.stack([t1, t2, t3], dim=0))
print(torch.stack([t1, t2, t3], dim=1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


# **Indexing and Aggregation Operations**

In [ ]:
t = torch.tensor([[1.,2.,3.],[4.,5.,6.]])

print(t.min(), t.max())
print(t.mean(), t.sum())
print(t.argmin(), t.argmax())  # index of min/max

# indexing (like NumPy)
print(t[0])          # first row
print(t[:, 1])       # second column
print(t[1, 2])       # single element

tensor(1.) tensor(6.)
tensor(3.5000) tensor(21.)
tensor(0) tensor(5)
tensor([1., 2., 3.])
tensor([2., 5.])
tensor(6.)


# **Data Types and Type Conversion**

In [ ]:
x = torch.tensor([1, 2, 3])
print(x.dtype)                      # torch.int64 by default

f = x.type(torch.float32)
print(f.dtype)

# or specify at creation
y = torch.tensor([1.0, 2.0], dtype=torch.float16)
print(y.dtype)

torch.int64
torch.float32
torch.float16


# **Transferring Tensors to GPU**

## Why Are GPUs Preferred for Machine Learning?

**CPUs (Central Processing Units)** are designed for general-purpose computing. They have a few powerful cores optimized for complex sequential tasks and instruction-level parallelism. Think of a CPU as a **few highly skilled experts** who can tackle diverse problems one after another very quickly.

**GPUs (Graphics Processing Units)**, on the other hand, are specialized for parallel processing. They have thousands of smaller, more efficient cores that can perform many simple calculations simultaneously. Imagine a GPU as a **vast army of specialized workers** who can all perform the same simple task at the exact same time.

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

t = torch.tensor([1., 2., 3.])
t_gpu = t.to(device)
print(t_gpu.device)

# move back to CPU (needed before NumPy conversion)
t_cpu = t_gpu.cpu()
print(t_cpu.numpy())

Using device: cpu
cpu
[1. 2. 3.]


## Discussion and Conclusion

In this notebook, we have explored fundamental concepts of PyTorch tensors and their operations. We have covered the following key areas:

*   **Introduction to Tensors**: We had started by importing the `torch` library and creating a basic 2x4 random tensor to illustrate its fundamental use.

*   **Tensor vs. Vector**: We had established a clear distinction between scalars, vectors, and general tensors. We had defined a scalar as a 0-dimensional tensor, a vector as a 1-dimensional tensor, and a tensor as a multi-dimensional array that generalizes these concepts.

*   **Tensor Creation Functions**: We had investigated various methods to create tensors using `torch` functions. This had included `torch.rand()` for random tensors, `torch.zeros()` and `torch.ones()` for tensors filled with specific values, `torch.eye()` for identity matrices, `torch.arange()` for sequences of numbers, and `torch.linspace()` for equally spaced points.

*   **Tensor Arithmetics**: We had explored arithmetic operations on tensors. We had differentiated between the `+` operator and `torch.add()` for addition, noting the latter's additional control over memory allocation and scaling. We had also distinguished between element-wise multiplication (`*`) and matrix multiplication (`@`), emphasizing their respective applications and shape requirements.

*   **Reshaping Tensors**: We had delved into `reshape()` and `view()` methods for changing tensor shapes. We had understood that `view()` creates a memory-shared view, requiring contiguity, while `reshape()` prefers a view but creates a copy if contiguity or memory layout does not allow for a view.

*   **Dimension Manipulation**: We had demonstrated `squeeze()` to remove dimensions of size 1 and `unsqueeze()` to add dimensions of size 1, which are crucial for preparing tensors for certain operations.

*   **Tensor Stacking**: We had used `torch.stack()` to concatenate a sequence of tensors along a new dimension, showcasing its utility in combining data.

*   **Indexing and Aggregation**: We had covered how to access specific elements or slices of tensors using indexing similar to NumPy. We had also performed basic aggregation operations like finding minimum, maximum, mean, sum, and the indices of minimum and maximum values.

*   **Datatype and Dtype Casting**: We had examined how to check and change the data types of tensors, highlighting the importance of data types for memory efficiency and compatibility with certain operations.

*   **Moving to GPU**: Finally, we had discussed the advantages of using GPUs for machine learning computations over CPUs due to their parallel processing capabilities. We had also demonstrated how to move tensors between the CPU and a CUDA-enabled GPU and back, which is essential for leveraging hardware acceleration.